### ISSUE TITLE
はじめにページのdescriptionを変える

### ISSUE THREAD

**Issue by yakitorii** [everyleaf/hotwire_ja#102]
https://everyleaf.github.io/hotwire_ja/turbo/handbook/introduction/
現状は以下
```html
<meta name="description" content="Turboは、クライアントサイドのJavaScriptフレームワークを使用することなく、高速でモダンなウェブアプリケーションを作成するためのいくつかの技術を提供します。">
```
本家のdescriptionを訳したものになるが、（SEO的に）よりよい文章に変更できるようならそうしたい。
修正ファイルは`turbo/handbook/introduction.md`

**Comment by otegami** [comment]
GH-113 で対応していただいたので close します。
