### ISSUE TITLE
タイトルの並び順変更

### ISSUE THREAD

**Issue by yakitorii** [everyleaf/hotwire_ja#104]
https://github.com/everyleaf/hotwire_ja/blob/198babaa07853c335b8c80f6536f44890596fef9/layouts/base.html#L11
`section_title ` は 「ハンドブック」などページのまとまり単位での名称、 `title` にページタイトルが入っている。
この並びだと、ブラウザタブは大概後半が見えなくなるので、どのページにいるかわかりづらくなる。逆順にしたい

**Comment by akira888** [comment]
secdtion_titleや、どのレイアウトファイルを使うのかはmdファイルを格納するディレクトリ内にある、`{パス名}.json`にて指定できるので、こちらも合わせて変更して大丈夫です。
section_codeだけは、collectionとしてのキーになるので気をつけてください

**Comment by yakitorii** [comment]
https://github.com/everyleaf/hotwire_ja/pull/114　で対応終了
