### ISSUE TITLE
jumplistのHOTWIREを「Hotwire リファレンス（有志翻訳版）」に

### ISSUE THREAD

**Issue by yakitorii** [everyleaf/hotwire_ja#106]
ユーザーやbotが見える範囲で「Hotwire リファレンス（有志翻訳版）」という文言を入れたい。
ただし現状のjumplistにあるHOTWIREのリンクは本家にジャンプするようになっているため、一旦リンクを消す必要がある。
（元々の想定では、このリンク先は翻訳版サイトのTOPページを作り、そこへジャンプさせたかった）

**Comment by akira888** [comment]
jumplistは[base.html](https://github.com/everyleaf/hotwire_ja/blob/198babaa07853c335b8c80f6536f44890596fef9/layouts/base.html)に直接書いている

**Comment by akira888** [comment]
対応済み
