### ISSUE TITLE
ページ内リンク調整

### ISSUE THREAD

**Issue by yakitorii** [everyleaf/hotwire_ja#5]
[`Turbo.se    tProgressBarDelay`](/reference/drive#turbodrivesetprogressbardelay)

といったリンクがある。
・日本語ページでのアンカー調整
・Handbookを公開してもreferenceはまだ公開していない時期にHandbook→referenceのリンクは原サイトへとリンクさせる
等の調整が必要

**Comment by akira888** [comment]
調整して公開したので閉じます。
ルールや仕組み化は別途進めます。
