### ISSUE TITLE
turbo/handbook/building.mdの差分更新

### ISSUE THREAD

**Issue by akira888** [everyleaf/hotwire_ja#62]
概要は https://github.com/everyleaf/hotwire_ja/issues/55 を参考にしてください。

**Comment by yasu551** [comment]
- 初回コミット日: 2023/7/31
- 初回コミット日に最も近いコミット
  - https://github.com/hotwired/turbo-site/commit/bede557cea90cf596f6cfb40003433a0b1817a91
- 初回コミットから、2024/07/09までの差分
  - https://github.com/hotwired/turbo-site/compare/bede557cea90cf596f6cfb40003433a0b1817a91..c2a19cd1d2b86f0be6d8d7f1d2e1f614fb100fcc

**Comment by yasu551** [comment]
初回コミットから、2024/07/09までの差分には、building.mdの変更はない。
なので、原文を追加するだけで良さそう
