### ISSUE TITLE
turbo/handbook/installing.mdの差分更新

### ISSUE THREAD

**Issue by akira888** [everyleaf/hotwire_ja#63]
概要は https://github.com/everyleaf/hotwire_ja/issues/55 を参考にしてください。

**Comment by akira888** [comment]
着手します

**Comment by akira888** [comment]
差分
https://github.com/hotwired/turbo-site/compare/26800eddd6dec7bd83d2eb6ad3c1c94b588b0d0f...0b2c287083c91402d44fd3075cc66bc1d8d8ee6e#diff-a99a54902b33ac76ebee57b681210074d59533c9350ccc906a7b236cbce6e10b

**Comment by akira888** [comment]
![Uploading スクリーンショット 2024-08-06 10.26.42.png…]()

**Comment by akira888** [comment]
<img width="1366" alt="スクリーンショット 2024-08-06 10 26 42" src="https://github.com/user-attachments/assets/bf007246-cb17-478c-ae7b-7830949ecc91">

**Comment by yakitorii** [comment]
Mergeされたので閉じます
