### ISSUE TITLE
page_refresh.mdのタイトルが「Hotwire」になってしまっている

### ISSUE THREAD

**Issue by akira888** [everyleaf/hotwire_ja#79]
サイドバーにファイルタイトルを出す仕組みにしているので、ページ内容が推測できなくなっている
![スクリーンショット 2024-09-17 11 00 57](https://github.com/user-attachments/assets/6a542d92-85f5-451b-8e02-1bb4fa518f37)

**Comment by otegami** [comment]
とりあえず、https://github.com/everyleaf/hotwire_ja/pull/84 にて、テスト用のCIを用意してみました。
もしもビルドされたページをテストしていくときは、このworkflowを拡張していくのはどうかなぁと想像しています。

**Comment by akira888** [comment]
PRとご提案、ありがとうございます！
とても良さそうなので、そうしていきたいです。
